import { createClient } from '@supabase/supabase-js'


export default createClient("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impzcnhsa29ienNtdmZ5cGNlcWpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjEwMjk3NjMsImV4cCI6MjAzNjYwNTc2M30.JJeCCFcQEEOpBqyCsbTQFO4dU_ZrUe1_nuE2jIV-BXI", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impzcnhsa29ienNtdmZ5cGNlcWpzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyMTAyOTc2MywiZXhwIjoyMDM2NjA1NzYzfQ.51KIssSG6P_o0NG8cLi0ajEe_pOTA33hfhiBtP7XFe0")
